
version: '3.7'

services:
  maria1:
    image: mariadb:10.4
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: password
    command: --wsrep-new-cluster
    ports:
      - '3306'
      - '4444'
      - '4567'
      - '4568'
    networks:
      - internal
    volumes:
      - ./maria1:/var/lib/mysql
      - ./backups:/backups
      - ./configs/maria1.cnf:/etc/mysql/mariadb.conf.d/config.cnf
  maria2:
    image: mariadb:10.4
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306'
      - '4444'
      - '4567'
      - '4568'
    networks:
      - internal
    volumes:
      - ./maria2:/var/lib/mysql
      - ./backups:/backups
      - ./configs/maria2.cnf:/etc/mysql/mariadb.conf.d/config.cnf
  maria3:
    image: mariadb:10.4
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306'
      - '4444'
      - '4567'
      - '4568'
    networks:
      - internal
    volumes:
      - ./maria3:/var/lib/mysql
      - ./backups:/backups
      - ./configs/maria3.cnf:/etc/mysql/mariadb.conf.d/config.cnf

networks:
  internal: